In [1]:
import numpy as np

sales_data = np.array([
    [120, 150, 180],
    [200, 220, 210],
    [100, 130, 140]
])

print("Sales Data:")
print(sales_data)

average_price = np.mean(sales_data)

print("\nAverage Price of Products Sold:", average_price)

Sales Data:
[[120 150 180]
 [200 220 210]
 [100 130 140]]

Average Price of Products Sold: 161.11111111111111
