In [3]:
import numpy as np

np.set_printoptions(suppress=True)

house_data = np.genfromtxt("house_data.csv", delimiter=",", skip_header=1)

filtered_houses = house_data[house_data[:, 0] > 4]

average_price = np.mean(filtered_houses[:, 2])

print("Houses with more than 4 bedrooms:")
print(filtered_houses)

print("\nAverage Sale Price:", round(average_price, 2))

Houses with more than 4 bedrooms:
[[     5.   2500. 550000.]
 [     6.   3200. 700000.]
 [     5.   2800. 600000.]]

Average Sale Price: 616666.67
